Repository QingTian1927/SSG104-Folks-AmeKane, pull requests merged in 2024-06, with the labels that each got.

#25 feat: updated navbar and footer.
  src/components/shared/footer.astro
  src/components/shared/navbar.astro
  tailwind.config.mjs
Labels: bug

#27 PR25-fixes
  src/components/shared/footer.astro
  src/components/shared/navbar.astro
  src/components/signin/loginField.astro
  src/pages/legal/[legal].astro
  src/pages/signin.astro
  tailwind.config.mjs
Labels: bug

#28 contact-page
  public/members/BVD.jpg
  public/members/Lmao.jpg
  public/members/gigachad.webp
  src/components/about/memberCard.astro
  src/components/shared/footer.astro
  src/components/shared/navbar.astro
  src/components/signin/loginField.astro
  src/i18n/ui.ts
  src/pages/about.astro
  src/pages/signin.astro
Labels: enhancement

#34 dashboard-home-sidebar
  src/components/dashboard/desktopSideBar/desktopSideBar.astro
  src/components/dashboard/desktopSideBar/navLink.astro
  src/i18n/ui.ts
  src/pages/dashboard.astro
Labels: enhancement

#36 mobile-navbar
  src/components/dashboard/mobileNavbar/bottomNavbar.astro
  src/components/dashboard/mobileNavbar/navLink.astro
  src/pages/dashboard.astro
Labels: enhancement

#37 feat: create 404 page
  src/pages/404.astro
Labels: enhancement, good first issue
